dist: xenial

language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install coveralls

script:
  - bandit --recursive confidence/
  - flake8 confidence/
  - coverage run --branch --source confidence --module py.test --strict tests/

after_success:
  - coveralls
