language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy3

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install coveralls

script:
  - flake8 confidence.py
  - coverage run --branch --source confidence --module py.test --strict tests/

after_success:
  - coveralls
